### ISSUE TITLE
Integrate with Sentry

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#100]
There should be optional support for Sentry, and we should use it in the version we distribute on hsreplay.net.

**Comment by jleclanche** [comment]
Depends on #91.

**Comment by beheh** [comment]
This is basically an HSReplay.net issue, I don't really want to add Sentry code to Joust. We should use the error callback from #91 to pass the exceptions to Sentry.

**Comment by jleclanche** [comment]
Sounds good.

J. Leclanche
