### ISSUE TITLE
Show "Cursed" card when it triggers

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#111]
https://hsreplay.net/games/replay/TCtFGnVwjqNyoMfpTv2j55 (see turn 4 friendly)

**Comment by Epix37** [comment]
This seems to just be a normal trigger block, so it would have to be hardcoded.

It will be displayed in the log though.

**Comment by jleclanche** [comment]
Doesn't have to be hardcoded - you can look at the source of the trigger and whether it has the `EVIL_GLOW` tag, i think.
