### ISSUE TITLE
"Wrapper div has no height or width" spam in the console when hovering minions

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#121]
raven.min.4999507b43e4.js:2 Wrapper div has no height or width, try overriding style with `containerStyle` option

**Comment by beheh** [comment]
Upstream issue: digidem/react-dimensions#40 (we're using flexbox too).

**Comment by beheh** [comment]
Fixed by digidem/react-dimensions#43, next upstream release should fix it.
