### ISSUE TITLE
Handle non-square textures

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#122]
Joust shouldn't assume square textures.

![image](https://cloud.githubusercontent.com/assets/235410/18115867/9b1bb460-6f4b-11e6-947b-bcc82db27ef8.png)

https://hsreplay.net/replay/avHw7bMDcbARKjfQxA47cm#turn=31a

**Comment by beheh** [comment]
There's really no simple fix for this, it's extremely tricky to maintain aspect ratio and crop images if we can't rely on them being square, portrait or landscape. Will probably not happen until we have a Javascript-based card renderer.

**Comment by jleclanche** [comment]
Alright, well I'm now generating 512x and 256x thumbnails which guarantee squareness.

Also, blizzard squareified the texture :)

**Comment by beheh** [comment]
:+1:

Closing for now, since it's not really feasible with the current renderer.
