### ISSUE TITLE
Implement HIDE_STATS

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#128]
The medivh brawl implemented `HIDE_STATS` which does the following:

- Hides health and attack from the minion token on the board
- Hides health and attack from the card render
- Does not render text for the mana gem.

**Comment by andburn** [comment]
Here's the no gem version of the frame:

![inplay_minion_no_gems](https://cloud.githubusercontent.com/assets/5419653/18185930/dccce1f2-7097-11e6-9ddc-96e53d80ee0b.png)
