### ISSUE TITLE
Display number of cards left in the deck when hovering the deck

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#13]

**Comment by beheh** [comment]
That should already be happening. It's a title-attribute which *should* be compatible with current browsers. It might take a second to pop up though, so maybe we want custom tooltips which show up instantly like in HS.

**Comment by jleclanche** [comment]
Yeah we want immediate tooltips.

**Comment by Epix37** [comment]
With https://github.com/HearthSim/joust/commit/18353c9864ad7536d7fd9d68b1e739f2f68a5aaf we now display the number of remaining cards directly on the deck, making this obsolete.
