### ISSUE TITLE
Add an option to download the game as JSON

### ISSUE THREAD

**Issue by Pikamander2** [HearthSim/joust#144]
XML is provided, but JSON would be nice as well

**Comment by jleclanche** [comment]
Thanks for the suggestion but we don't use JSON for the games at all, and it's not something we'll do. We have a different JSON-based spec, but it's meant to be used for transferring game state live, whereas HSReplay XML is a nested format which has a much stricter spec:

https://hearthsim.info/hsreplay/

Also, this repository is specifically dedicated to the replayer component. If you have feedback/suggestions on HSReplay.net itself, you can [file it on the subreddit](https://www.reddit.com/r/hsreplay) or if you find any bugs with the site itself, the correct repository to use is [HearthSim/HSReplay.net](https://github.com/hearthsim/hsreplay.net)
