### ISSUE TITLE
Frozen not showing up on heroes

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#156]
Example replay:  https://hsreplay.net/replay/sp5smCGpsV9gqWKmG8x9Go#turn=18a

**Comment by jleclanche** [comment]
Ref #7

**Comment by jleclanche** [comment]
I wonder if we can reuse the same asset as minions with some css transforms.

**Comment by beheh** [comment]
Fixed by #162, even if it looks... slightly weird without the spikes. That'll need a rework of the hero component though, and we'll lose some vertical space (it's currently borderless, that's also why the secret "?" doesn't exceed outside the edge).
