### ISSUE TITLE
Attempt to detect The Coin entity

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#163]
https://hsreplay.net/replay/N6fQX5eCpWAisBDjUpEBha

It's interesting we hit that. We can very likely figure the coin out:

- `FULL_ENTITY` directly into `ZONE` == `HAND`
- Game `STEP` is null
- `CONTROLLER` is not `FIRST_PLAYER`
- `ZONE_POSITION` == `5`

If it meets all these, then the oracle can make a safe guess about the coin, I think. It does have to meet all of them just to make sure we don't mistakenly hit a tavern brawl or some such.

**Comment by beheh** [comment]
Superseeds the fix for #85 (3bc6d082aa757f1c026bda58f3cc581298822ce3).
