### ISSUE TITLE
Concede incorrectly counted as a lose

### ISSUE THREAD

**Issue by williamwebb** [HearthSim/Joust#185]
https://hsreplay.net/replay/5Ma4qYotLGsTSAbw8X6L8K

Might be the uploaded data was incomplete since the event log does not show the opponent conceding. I would think in the event that no winner is clear it would reflect that not assume a lose.

**Comment by azeier** [comment]
That looks like an incomplete upload to me.

I think this is a known hstracker issue? @jleclanche @bmichotte

**Comment by bmichotte** [comment]
Yep, HSTracker sends the log a little bit too early. It (will|should) be corrected in the next release.

**Comment by azeier** [comment]
:+1:

Closing this then since it's not a joust issue.
