### ISSUE TITLE
Hearthstone Deck Tracker - cards limit (7)

### ISSUE THREAD

**Issue by maky22** [HearthSim/Joust#187]
Why in replays I can only see cards up to 7 but more powerfull does not show in decks (but in replay - yes)?

**Comment by beheh** [comment]
I'm not sure what you mean. Do you mean the mana cost? Do you mean decklists? Can you share a screenshot of where you expect the cards?

**Comment by maky22** [comment]
On the right there are players deck with cards played during the game. Some of the cards do not show. When I go thru replay this cards are used. I noticed that this is problem with Hearthstone Deck Tracker. In this ap is the same (fragment) of deck (deck = played cards, not all cards).

**Comment by maky22** [comment]
https://hsreplay.net/replay/oTeNH33xWBwLtVWqTSPaER

Move 12 - Medivh, the Guardian

**Comment by beheh** [comment]
The replays work bit different, since we only show the starting deck on the side right now. Otherwise same as #188.

**Comment by maky22** [comment]
I understand it now. Thank You.
