### ISSUE TITLE
Do not see in deck all oponent cards used in fight...

### ISSUE THREAD

**Issue by maky22** [HearthSim/Joust#188]
Do not see in deck all oponent cards used in fight...

Just see replay and oponent deck on the right.

**Comment by beheh** [comment]
Can you link the replay, please?

**Comment by maky22** [comment]
https://hsreplay.net/replay/oTeNH33xWBwLtVWqTSPaER

Move 12 - Medivh, the Guardian

**Comment by maky22** [comment]
https://hsreplay.net/replay/cGarGKg6vnfHiFoyA9QaWP

**Comment by maky22** [comment]
Maybe HRSreplay.net should analyze fight and create decks, not only import?

**Comment by beheh** [comment]
@maky22 In both those games, the opponent has Prince Malchezaar, which creates legendaries at the start of the game - thus, they are not part of the deck. We might add the live updated decks (similar to how the Deck Tracker adds generated cards to your deck) at some point, but that's out of scope for now.

**Comment by maky22** [comment]
Thank You. I just got it by myself. :)
