### ISSUE TITLE
Wrong oponent class

### ISSUE THREAD

**Issue by maky22** [HearthSim/Joust#189]
https://hsreplay.net/replay/sdaNDx2DrkqNfJejzJRvUT

My oponent was a Mage but if I copy deck of him I get:

{"name":"kataphrakt's Rogue","class":"Rogue","card_ids":["EX1_284","CS2_027","EX1_277","EX1_277","CS2_029","EX1_608","EX1_608","CS2_024","NEW1_012","NEW1_012","CS2_023"],"sourceUrl":"https://hsreplay.net/replay/sdaNDx2DrkqNfJejzJRvUT"}

**Comment by azeier** [comment]
Issue moved to [HearthSim/HSReplay.net #129](https://github.com/HearthSim/HSReplay.net/issues/129) via [**ZenHub**](https://www.zenhub.com/)

**Comment by azeier** [comment]
@maky22 Thanks! I'll fix that later tonight
