### ISSUE TITLE
Add quests

### ISSUE THREAD

**Issue by beheh** [HearthSim/Joust#193]

**Comment by briangordon** [comment]
To add a little color: when a quest card is played, the secret icon appears but no played card appears and the event log on the right says nothing about it.

**Comment by jleclanche** [comment]
Mobile screenshot

![image](https://cloud.githubusercontent.com/assets/235410/24927184/c8ebedfe-1f06-11e7-9d86-f80fe21ecc74.png)

**Comment by beheh** [comment]
Was done.
