### ISSUE TITLE
Show Deck doesn't work

### ISSUE THREAD

**Issue by zozzy** [HearthSim/Joust#195]
It doesn't show my deck which I played at the replay.. It shows random cards I think..!!!

**Comment by jleclanche** [comment]
Link?

**Comment by zozzy** [comment]
https://hsreplay.net/replay/97tFE9njZafa6PZNJPbCbB

**Comment by jleclanche** [comment]
This is a known issue with certain Tavern Brawl decks. There's not a ton we can do about it, but we're tracking it in the HSReplay.net repository.

**Comment by jleclanche** [comment]
Issue moved to [HearthSim/HSReplay.net #278](https://github.com/HearthSim/HSReplay.net/issues/278) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zozzy** [comment]
Too bad. I especially played these tawern brawl games with deck tracker to know which cards I need to build these brawl decks!

**Comment by jleclanche** [comment]
@zozzy The decks for this week's brawl are the same as the ones for all the un'goro deck recipes. You can find them when you create a new deck, it's the rightmost recipe!

**Comment by zozzy** [comment]
Rly? thanks for info m8.
