### ISSUE TITLE
Expose player deck lists

### ISSUE THREAD

**Issue by beheh** [HearthSim/Joust#198]
So we can show full decklists outside of Joust.

This will allow us to use partial decks from Joust instead of HSReplay.net and drop them from the HSReplay.net deck.

**Comment by joolean** [comment]
Doesn't seem valuable at this moment to eject replay parsing into a separate library. So we'll just do this via bidirectional communication between Joust and the HSReplay.net replay frame.

**Comment by azeier** [comment]
Isn't that what this ticket is?

**Comment by jleclanche** [comment]
Yes, it is.

**Comment by joolean** [comment]
That was a reminder to myself re: a question I asked Benedict about this ticket. :smile: Closing to merge this one with HSReplay.net#290...
