### ISSUE TITLE
Error loading replay, Try Again.

### ISSUE THREAD

**Issue by Ghosty141** [HearthSim/Joust#205]
If I try to watch any of my replays I just face this screen: http://i.imgur.com/yBbL1Yh.png

It did work like a few weeks ago, but somehow not anymore. Any help would be appreciated.

Running Firefox 55.0.3 64 bit, Windows 10 64bit, ISP: Vodafone (Germany).
One of my replays for example: https://hsreplay.net/replay/5EZqRZNa2a6qhUjuoe7a3W

**Comment by riQQ** [comment]
Works for me. Probably Adblock or something related.

**Comment by Ghosty141** [comment]
You were right, ublock prevented it from working. Probably related to a recent update.
