### ISSUE TITLE
Allow viewers to configure font

### ISSUE THREAD

**Issue by frozenspider** [HearthSim/Joust#209]
`franklin_gothic_fsMdCn` (or whatever is the name of that font) looks absolutely horrible when font smoothing (and, possibly, some other default tweaks) is off. I think ability to configure font and its size will be in order.
![Screenshot](https://screenshots.firefoxusercontent.com/images/27f81c0d-6558-4066-94bd-c203cf675361.png)

**Comment by jleclanche** [comment]
I mean, don't disable font smoothing then :/
If you still do want to disable font smoothing you can also prevent HSReplay.net from using custom fonts / webfonts. That will do the trick. But I don't see us adding an option to customize the font.
