### ISSUE TITLE
Broken replay

### ISSUE THREAD

**Issue by disbelieveordoubt** [HearthSim/Joust#217]
Example: https://hsreplay.net/replay/EnocQ2y3AqFJuWReKwMHRP#

**Comment by beheh** [comment]
Thanks for your report. What specifically is broken about the replay? It loads and shows just fine on my end.

**Comment by disbelieveordoubt** [comment]
After I played, the replay gave an error and would t work. I used the
reporting function - no moves were replayable without an error.

I tried watching immediately..

**Comment by disbelieveordoubt** [comment]
Benedict,

I just checked this link again, and the replay errors for me.
https://hsreplay.net/replay/xmXjrGbmqtE8Jj5d3JiZF9

Here's the error I get:

[image: Inline image 1]

**Comment by beheh** [comment]
Could you possibly send a screenshot of the full error?

**Comment by disbelieveordoubt** [comment]
It looks like the error has been fixed!  The replay was loading just fine
in Firefox after I sent the last message, and now it's fixed in Chrome!
Thanks!

**Comment by beheh** [comment]
I'm not aware of any related changes. Possibly you just had a bad version in your cache. Either way, good to hear it's fixed!
