### ISSUE TITLE
"Link to current turn" sharing option has no effect

### ISSUE THREAD

**Issue by carloscbz** [HearthSim/Joust#225]
When sharing a replay, the URL does not change when selecting the option "Link to current turn", so the replay always starts from the beggining.

I tested it with Firefox 61 and Chrome 67. Tested cases:

- Copying the URL manually
- Copying the URL with the "Copy" button
- Clicking the Reddit share button
- Clicking the Twitter share button

In all cases the URL is the same and the replay does not start at selected turn.

**Comment by beheh** [comment]
Thanks for the report! This duplicates HearthSim/HSReplay.net#857, but thanks for the test cases!
