### ISSUE TITLE
Interaction bug - "Maxima Blasterhelmer" and "C`Tun"

### ISSUE THREAD

**Issue by Saabwey** [HearthSim/Joust#247]
Opponent upgraded C`Tun by + 2 / + 2 on turn 4. At 6 turn he played "Maxima Blasterhelmer". What happened next you just need to see https://hsreplay.net/replay/RUDnsUqKX72chbj7cQW9yZ

**Comment by beheh** [comment]
Hello, I think you're reporting a Hearthstone bug. This is a community repository for the replay applet on HSReplay.net, and we can't fix any Hearthstone issues.
