### ISSUE TITLE
Figure out font licenses

### ISSUE THREAD

**Issue by beheh** [HearthSim/joust#26]
We should figure out the licenses for:
- [x] Belwe Bd BT
- [x] Franklin Gothic Condensed

**Comment by andburn** [comment]
I should've checked this before adding them :grimacing:

[Belwe Bold (Bitsream)](http://www.myfonts.com/fonts/bitstream/belwe/bold/)
[Franklin Gothic Condensed (URW)](https://www.myfonts.com/fonts/urw/franklin-gothic/t-medium-condensed/)

Unsurprisingly, they are both commercial.
I'll try to find some non-commercial ones that we can substitute.

**Comment by Mischanix** [comment]
Looking on google fonts for something like Belwe bold led to Eczar, weight 800

[Example](https://htmlpreview.github.io/?https://gist.githubusercontent.com/Mischanix/9f2cb96c82e10e827f16/raw/f9c47568195326bfd3d4fef4f0fbb3ec51aed4f2/ex.html)

**Comment by andburn** [comment]
I was going to suggest [Merriweather, 900](https://www.google.com/fonts/specimen/Merriweather), but [Eczar](https://www.google.com/fonts/specimen/Eczar) does look more interesting.
[Roboto, 500](https://www.google.com/fonts/specimen/Roboto) should do fine to replace Franklin for the description text.

**Comment by Epix37** [comment]
Where are we on this?

**Comment by beheh** [comment]
I haven't tried them in the applet yet, but I'll test them soon.

**Comment by Epix37** [comment]
The two links I posted in discord yesterday:
- https://www.fontspring.com/fonts/fontsite/belwe-fs
- https://www.fontspring.com/fonts/fontsite/franklin-gothic-fs

Both very cheap, with unlimited monthly page views (shown when font is added to cart). The [license](https://www.fontspring.com/lic/lv4e5lv2k2) sounds a lot better than the MyFonts one.

**Comment by beheh** [comment]
Closed with b22f18bd074fe429b71e484227b21241a9d61121.
