### ISSUE TITLE
Allow Replay playback to be paused and/or stepped forward manually

### ISSUE THREAD

**Issue by smallnamespace** [HearthSim/joust#3]
Allow Replay playback to be paused and/or stepped forward manually:

Basically some actions are a bit complicated and it's easy to miss what happened, so it would be nice to be able to pause.

**Comment by smallnamespace** [comment]
I'm willing to work on this myself, but I need to get up to speed on reading React code

**Comment by beheh** [comment]
Duplicate of #4.
