### ISSUE TITLE
Add keyboard bindings

### ISSUE THREAD

**Issue by beheh** [HearthSim/joust#30]
- [x] Play/Pause: Space/K
- [x] Swap perspective: C
- [x] Scrub forwards/backwards: J/L left/right
- [x] Reveal/Hide cads: X
- other wishes?

**Comment by Epix37** [comment]
Maybe ctrl + left/right to skip to prev/next turn?

**Comment by beheh** [comment]
We're now using left/right to skip to prev/next turn. In future we'll use up/down to skip to prev/next action.
