### ISSUE TITLE
Implement viewing multiple games as one game

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#31]
This will implement "reconnect" feature for replays. If there is more than one game in a replay, and the second game has the **same id attribute** as the first game, the second game is considered to "continue" the first one.

**Comment by beheh** [comment]
This should be pretty trivial.

**Comment by Epix37** [comment]
Here's an example: http://hsreplayarchive.org/joust/replay/d43a810d-3b40-419f-ad8b-0aa57a47cc31
