### ISSUE TITLE
Add basic UI zone delimitations

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#34]
* [x] Add a border between the two sides of the battlefield
* [x] Add a border between the battlefield and the hero box
* [x] Add borders between hand and hero box

Once we have clearer delimitations between the zones we can prototype with various styles (eg. different background colors for the hand so it's clearly "outside" the rest of the field).

**Comment by Epix37** [comment]
Added with https://github.com/HearthSim/joust/commit/18353c9864ad7536d7fd9d68b1e739f2f68a5aaf.
