### ISSUE TITLE
Add deck graphics

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#38]
Like Hearthstone, the deck should appear as a thick stack of cards that gets thinner as the deck itself thins.

**Comment by jleclanche** [comment]
As discussed on Discord, we'll be going with a face-down pile instead of a vertical slot like HS does it.

**Comment by Epix37** [comment]
This was implemented with https://github.com/HearthSim/joust/commit/18353c9864ad7536d7fd9d68b1e739f2f68a5aaf.
