### ISSUE TITLE
Make "End Turn" a "Next Turn" button in replay mode

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#39]
In replay mode, the "End Turn" button should become a "Next Turn" button which immediately skips to the next turn.

**Comment by jleclanche** [comment]
I'm thinking maybe we can have a "Previous Turn" button as well next to it. Basically it'd look like turn controls, except it'd be outside of the bottom control bar.

**Comment by Epix37** [comment]
Removed end turn button with https://github.com/HearthSim/joust/commit/b1ef35b1ff6251080723aeed1c7586153dc08433.
