### ISSUE TITLE
Add a scrubber for the current game

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#4]
There should be a progress bar at the top allowing you to quickly seek to other parts of the game.

**Comment by beheh** [comment]
This is trivial with the game state scrubber. I'd also like actions marked on the bar, similar to the joust1 prototype.

**Comment by jleclanche** [comment]
I'd specifically like a turn marker of sorts, maybe of a different color depending on whose turn it is.

The UI I'm thinking is like, you have a progress bar which is green when it's the bottom player's turn and blue when it's the top player's turn. And when you drag the needle, you have a tooltip that says "Turn X".

**Comment by beheh** [comment]
Related to #3.

**Comment by beheh** [comment]
Playing, pausing and rewinding works. Working on the actual scrubber now.

**Comment by beheh** [comment]
Done. Tracking colored parts at #29.
