### ISSUE TITLE
Redesign End Turn button

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#40]
The button should be larger, have more padding and be styled a little more like Hearthstone (bold black on yellow/green? Experimentation needed)

**Comment by Epix37** [comment]
Maybe also change the text to "Playername's turn" instead of "end turn" (at least for replays)?

**Comment by Epix37** [comment]
How about using the same colors we use for the scrubber (#29)? Would also be a less extreme approach for #41 at the same time.

**Comment by beheh** [comment]
The current plan is to color the player's names on the left side.

**Comment by Epix37** [comment]
Removed end turn button with https://github.com/HearthSim/joust/commit/b1ef35b1ff6251080723aeed1c7586153dc08433.
