### ISSUE TITLE
Highlight the side of the board whose current turn it is

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#41]
I'm curious to try out various approaches to that. Either making the current hero glow, or give the current player's side of the battlefield a different background color...

**Comment by beheh** [comment]
I'm not sure I like this too much. Aren't the options obvious enough?

**Comment by jleclanche** [comment]
There aren't necessarily any options.

**Comment by beheh** [comment]
Hm, #40 should always be correct then. But let's try. We could also do stuff with CSS filters, like black/white cards for the inactive player or something.

**Comment by jleclanche** [comment]
That would be amiss if the player has no more cards.

**Comment by beheh** [comment]
I meant including the hero and all UI elements and stuff. I'll try a few things out.

**Comment by Epix37** [comment]
Added with https://github.com/HearthSim/joust/commit/18353c9864ad7536d7fd9d68b1e739f2f68a5aaf. Still needs some adjustment though.
