### ISSUE TITLE
Card text scales with viewport height, rather than applet size

### ISSUE THREAD

**Issue by andburn** [HearthSim/joust#53]
Scaling the whole card component with a css transform seems like best solution. The percentage based text alignment isn't very accurate anyway.

Depends somewhat on the decision of #51.

**Comment by beheh** [comment]
I'm working on this right now.

**Comment by beheh** [comment]
I won't be able to finish this tonight, but I'm reworking the full CSS. The main problem was using the `vh` size parameter - it's relative to the viewport height, not the container height. We might have to fallback to FitText or something.

**Comment by andburn** [comment]
Ok, sure. Won't touch any of it until your finished :smile:

**Comment by beheh** [comment]
This is no issue right now with the new layout.
