### ISSUE TITLE
Darken entire board during mulligan

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#76]
Currently the first player's board is highlighted during mulligan. We should darken the entire board, possibly even more than the usual "inactive" bit.

**Comment by Epix37** [comment]
No current player highlight until mulligan is over, 75% grayscale and 3px blur for player during choices: http://imgur.com/a/e8Wu4

Not too sure on those numbers but I like the direction, might be worth considering to blur both players during any choices. The blur also has the added sideeffect that it distracts from the asymmetry a bit.

**Comment by jleclanche** [comment]
I like it. I'm not sure we should be moving the hands once they are ready before mulligan is over (cf. how hearthstone does it),but that's another issue.

**Comment by Epix37** [comment]
I talked to benedict about that before. IIRC, it's something that doesn't have a non-hacky solution until we have actions.
