### ISSUE TITLE
Always show a hero

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#77]
At the end of the game, the hero disappears. This might not be easy to do but when a hero entity is absent, we should grey out the most recent hero entity instead of removing it altogether.

**Comment by jleclanche** [comment]
Possibly we could just grey out the hero frame and have nothing in it if it's easier to do that way.

**Comment by Epix37** [comment]
#75 solves this.

**Comment by Epix37** [comment]
Fixed with https://github.com/HearthSim/joust/commit/9846a3799a23d6662aeb31098200453c795fed3d
