### ISSUE TITLE
The Coin still shows up during mulligan with the card oracle turned off

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#85]
If I turn off the card oracle, I see 5 cards in the opponent's hand during Mulligan.

Also happens if the opponent didn't use the coin at all:

http://hsreplay.net/joust/replay/153df268-5d2f-403a-9d57-91815527f941

**Comment by beheh** [comment]
Hm, there is no simple fix here apart from hiding all cards that are unknown, or maybe trying to guess the correct number of cards and hide superfluos ones.

**Comment by jleclanche** [comment]
Hearthstone manages, somehow. I think HS assumes you cannot have more than a certain amount of cards in mulligan and hides anything past 4 cards.

**Comment by beheh** [comment]
This is now also supported by the card oracle always being available.

**Comment by beheh** [comment]
Superseeded by #163 (72ffd4cf91883a86f62b2eebe646e0970c3567e6).
