### ISSUE TITLE
Create jpg art renders optimized for joust

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#9]
Also figure out where to serve them from.

**Comment by beheh** [comment]
So, @andburn's system has added card outlines and some special stuff (like legendary and taunt graphics). We basically just need the raw card art now, the frame and everything else (like dynamic cost, numbers, description...) is rendered by Joust.

**Comment by beheh** [comment]
We're using the PNG art right now. Still open:
- [ ] some textures seem to be missing in HSReplay (Shredder...)
- [ ] some texture files are missing in the texture folder (Heroes textures, but also some minions)

**Comment by Epix37** [comment]
I think this is all done?

**Comment by jleclanche** [comment]
Yes
