### ISSUE TITLE
Layout rework

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#90]
Some more design brainstorming on the layout

![image](https://cloud.githubusercontent.com/assets/235410/15058090/08ecb7bc-1323-11e6-9d44-74c829ffb5b4.png)

**Comment by jleclanche** [comment]
Main changes discussed:

- Moving the hero on the left
- Which allows us to stop centering the hand, left-aligning it instead
- Adding a "next card" when available
- Adding a "TURN X" between the decks (already tracked in another bug)
- Moving the player name below the hero portrait (maybe)
- ... which would let us use a single-crystal (phone-style) mana tray.

**Comment by jleclanche** [comment]
![image](https://cloud.githubusercontent.com/assets/235410/15060279/b910be1e-1331-11e6-839d-0b9c26d7cce9.png)

**Comment by Epix37** [comment]
This might be a starting point for a scrubber design:

![b910be1e-1331-11e6-839d-0b9c26d7cce91](https://cloud.githubusercontent.com/assets/7737910/15061924/2085d008-133b-11e6-93d2-e9c2d85fa3b2.png)

It does seem a bit too noisy as-is. Maybe 66-75% height instead of 50% could work better. *Or* Just having one of the rows.

**Comment by beheh** [comment]
The blue color is a big change and might take some time getting used to.

In general I'm happy with flipping the equipment area to the left, I'm not entirely sure on the left align, especially with few cards:

![Few cards and left-aligned](http://i.imgur.com/U0sATuz.jpg)

Also, should the turn indicator move around to the currently active player?

The half-height scrubber sections are really nice, and I like them. We'll just flip them if you swap the players, so they should always match.

**Comment by Epix37** [comment]
Adding "shadows" for empty spots in the hand could help with lower card counts: 
![b910be1e-1331-11e6-839d-0b9c26d7cce92](https://cloud.githubusercontent.com/assets/7737910/15069803/73df45fa-1380-11e6-9aee-f20785ac4683.png)

Also added a very subtle line separating the hand and board for the inactive player.

**Comment by jleclanche** [comment]
-1 on the card shadows.

Very few cards should be spaced out further, until it no longer looks comfortable.

**Comment by jleclanche** [comment]
BTW the main reason it's so wide is so that joust is the same aspect ratio as youtube.

**Comment by beheh** [comment]
Basics are done for now.
