### ISSUE TITLE
Log error if unknown card id is found

### ISSUE THREAD

**Issue by beheh** [HearthSim/Joust#92]

**Comment by jleclanche** [comment]
Can you log an exception as well? (which we will send to sentry)

**Comment by beheh** [comment]
Yep, refs #91.

**Comment by beheh** [comment]
Actually, the fallback to `/latest` should rather happen on hsreplaynet when `/<buildnum>` 404s. Error reporting in Joust should stay though

**Comment by jleclanche** [comment]
@beheh what's the status on this? If not done, can we have it ready before Kobolds?

**Comment by jleclanche** [comment]
Looks like we won't need to do this.
