### ISSUE TITLE
Display "damage taken" value on minions/heroes

### ISSUE THREAD

**Issue by Epix37** [HearthSim/joust#95]
from attacks/spells

**Comment by beheh** [comment]
Will be using the GameStateDescriptor, but we'll have to build another entity-id-tree (player->zone).

**Comment by Epix37** [comment]
Basic concept implemented with https://github.com/HearthSim/joust/commit/472e123e0b56c4d15ee51d73c1539688ea4262f1.

Todo:
- adjust text size
- full rewrite / refactoring
