### ISSUE TITLE
Fail gracefully when failing to load replay file

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Joust#97]
Right now, if CROS isn't configured correctly for example, this is what we get:

`bundle.js:15 Uncaught Error: Network errort.onerror @ bundle.js:15`

**Comment by jleclanche** [comment]
We'll need to hook this up to sentry somehow once we get that part set up. But for the time being, displaying a proper error message would be nice.

**Comment by beheh** [comment]
Refs #91.

**Comment by beheh** [comment]
We apparently seem to be redirecting when an empty url is loaded `.fromUrl("")`.

**Comment by beheh** [comment]
Refs #82.

**Comment by beheh** [comment]
https://app.getsentry.com/hearthsim/joust/issues/147448072/
